### ISSUE TITLE
add item with submenu in ps_mainmenu.tpl

### ISSUE THREAD

**Issue by tiptopnet** [PrestaShop/ps_mainmenu#26]
Hi

I use Prestashop 1.7.5.2 and I need to add add item with submenu in ps_mainmenu.tpl, at the end (right)

With the BO I can add an item (cms page) but no submenu possible

Thanks for your help

Attached tpl file
[ps_mainmenu.txt](https://github.com/PrestaShop/ps_mainmenu/files/3550090/ps_mainmenu.txt)

**Comment by khouloudbelguith** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/15290
